### ISSUE TITLE
it doesn't work with API tokens

### ISSUE THREAD

**Issue by Jerome2103** [MrMissx/Telegram_Forwarder#43]
I need help :(

He has all admin rights and no restrictions have been made
It works via telephone number. but is very ugly

user@server:/path/to/telegram_bot$ python3 forwardgram.py config.yml
Please enter your phone (or bot token): HERE API Token
Traceback (most recent call last):
  File "forwardgram.py", line 49, in <module>
    start(config)
  File "forwardgram.py", line 20, in start
    for d in client.iter_dialogs():
  File "/home/user/.local/lib/python3.8/site-packages/telethon/requestiter.py", line 87, in __next__
    return self.client.loop.run_until_complete(self.__anext__())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.8/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/dialogs.py", line 53, in _load_next_chunk
    r = await self.client(self.request)
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/user/.local/lib/python3.8/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by GetDialogsRequest)
user@server:/path/to/telegram_bot

**Comment by MrMissx** [comment]
I don't think that come from this repo.
here we use Python-Telegram-Bot not Telethon
